### ISSUE TITLE
Specify ocaml bound and correct dune bound

### ISSUE THREAD

**Issue by kyoDralliam** [dlesbre/coq-prettier-makefile#1]
The versions indicated in the `coqprettiermakefile.opam` are not correctly set: 
- the constraint `dune >= 3.4` is not compatible with `(lang-dune 3.6)` in `dune-project`;
- no (ocaml) version is specified for the Stdlib and  the code uses `String.starts_with` and `String.ends_with` introduced in `4.13` and the module `Either` introduced in `4.12`.

**Comment by dlesbre** [comment]
Thanks for pointing this out. I've remove these small functions to have compatibility from ocaml 4.10.x -- 4.14.x and specified these bounds.

The lower version bound is now set by `Filename.quote_command` which is much harder to do without. Plus Ocaml 4.10 dates back to February 2020, so hopefully most users have upgraded since.
