### ISSUE TITLE
Subdirectories and `make -C`

### ISSUE THREAD

**Issue by kyoDralliam** [dlesbre/coq-prettier-makefile#2]
It looks like call to `make -C subdir` can crash `coq-prettier-makefile` when there is an error in one of the subdirectory.
Here's a test case to reproduce the error. The test directory contains a coq library and a subidrectory `B` that contains itself a coq library. The error in the file `B/theories/BB.v` yield the following trace:
```
/test> coq-make
Compiling whole projectFinding dependencies with coqdep for VFILES
File "theories/BB.v", line 3, characters 20-23
Fatal error: exception Sys_error("theories/BB.v: No such file or directory")
```

[testSubdir.tar.gz](https://github.com/dlesbre/coq-prettier-makefile/files/13648478/testSubdir.tar.gz)

Could the error be handled as a warning ?

**Comment by dlesbre** [comment]
This bug was due to make's CWD change, which leads to invalid file name in `coq-make`'s CWD appearing. coq-make then failed when trying open the file (to print the line where the error occured).

I added a catch-all error to file opening (still can't believe I can't find the list of exceptions `open_in` will raise anywhere... gotta love OCaml's documentations).

I also added some code to better handle working directory change. `coq-make` should be able to print your file in the subfolder as `B/theories/BB` and not just `theories/BB`, and open it correctly to display the error line. This logic will fail if there are duplicates though... If there is a `BB.v` in `./theories`  and one in `./B/theories`, they are impossible to distinguish from `make`'s output.
